global using System.Collections.Immutable;
global using Aqeem.DataContracts;
global using Aqeem.DataContracts.Serialization;
global using Aqeem.Models;
global using Aqeem.Presentation;
global using Aqeem.Services.Caching;
global using Aqeem.Services.Endpoints;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
